"""Initial schema

Revision ID: a4f60831956b
Revises: 
Create Date: 2025-08-28 19:20:54.383299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4f60831956b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('elevation_gain_m', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('elevation_loss_m', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('max_speed_ms', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('avg_speed_ms', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('min_heart_rate', sa.Integer(), nullable=True),
    sa.Column('gpx_file_path', sa.String(length=500), nullable=True),
    sa.Column('total_trackpoints', sa.Integer(), nullable=True),
    sa.Column('valid_hr_trackpoints', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('analysis_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=50), nullable=True),
    sa.Column('start_point_order', sa.Integer(), nullable=True),
    sa.Column('end_point_order', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('avg_pace_min_per_km', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_segments_id'), 'analysis_segments', ['id'], unique=False)
    op.create_table('analytics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_version', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_cache_id'), 'analytics_cache', ['id'], unique=False)
    op.create_index('ix_sporter_analytics_cache_lookup', 'analytics_cache', ['activity_id', 'metric_type', 'parameters'], unique=False)
    op.create_table('trackpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('point_order', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('elevation', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('speed_ms', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('exclude_from_hr_analysis', sa.Boolean(), nullable=True),
    sa.Column('exclude_from_gps_analysis', sa.Boolean(), nullable=True),
    sa.Column('exclude_from_pace_analysis', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('is_stationary', sa.Boolean(), nullable=True),
    sa.Column('distance_from_previous_m', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('time_gap_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed duplicate coordinate index - using custom ix_sporter_trackpoints_coords_gist instead
    op.create_index('ix_sporter_trackpoints_activity_order', 'trackpoints', ['activity_id', 'point_order'], unique=False)
    op.create_index('ix_sporter_trackpoints_coords_gist', 'trackpoints', ['coordinates'], unique=False, postgresql_using='gist')
    op.create_index('ix_sporter_trackpoints_hr_analysis', 'trackpoints', ['activity_id', 'exclude_from_hr_analysis'], unique=False)
    op.create_index('ix_sporter_trackpoints_recorded_at', 'trackpoints', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_trackpoints_id'), 'trackpoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackpoints_id'), table_name='trackpoints')
    op.drop_index('ix_sporter_trackpoints_recorded_at', table_name='trackpoints')
    op.drop_index('ix_sporter_trackpoints_hr_analysis', table_name='trackpoints')
    op.drop_index('ix_sporter_trackpoints_coords_gist', table_name='trackpoints', postgresql_using='gist')
    op.drop_index('ix_sporter_trackpoints_activity_order', table_name='trackpoints')
    # Removed duplicate coordinate index drop
    op.drop_table('trackpoints')
    op.drop_index('ix_sporter_analytics_cache_lookup', table_name='analytics_cache')
    op.drop_index(op.f('ix_analytics_cache_id'), table_name='analytics_cache')
    op.drop_table('analytics_cache')
    op.drop_index(op.f('ix_analysis_segments_id'), table_name='analysis_segments')
    op.drop_table('analysis_segments')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###